version: "3.8"

services: 
  model: 
    build: ./service_model
    ports:
      - 5001:5001
  # store:
  #   image: #pull the store vector image
  #   ports:
  #     - 2222:2222 #to find
  #   volumes:
  #     -assignment: #then find where the data is put with this image. e.g. assignment:/data/db
  api:
    build: ./service_API
    ports:
      - 5002:5002
    # environment: #to find, depends on the vector store. ex:mongodb://store

# volumes:
#   assignment: