version: "3.8"

services: 
  model: 
    build: ./service_model
    ports:
      - 5001:5001


  store:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    ports:
      - 9200:9200
    environment:
      - node.name=store
      - discovery.type=single-node
    volumes:
      - ./service_vec_store/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml #allows to take a custom yml config for elastic search and allow simple http requests (instead of https)

  api:
    build: ./service_API
    ports:
      - 5002:5002
